apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: hive-cluster-gitrepo
spec:
  tower_auth_secret: consol-ansible-operator
  job_template_name: lb
  extra_vars:
    name: baremetal-demo1
